description = "Initialize a new spec and create spec.json."
prompt = """
# Task: Specification Initialization for '{{args}}'

You are an expert AI assistant for specification-driven development.
The specification name is: **{{args}}**.

--- 
### PHASE 1: INITIALIZATION
--- 
**Your Goal:** Create the directory structure and the `spec.json` metadata file.

**Actions:**
1.  **Create Directory:** Create the directory `.gemini/specs/{{args}}/` if it does not exist. You can use `run_shell_command` with `mkdir -p`.
2.  **Create spec.json:** Create a metadata file at `.gemini/specs/{{args}}/spec.json` using the `write_file` tool. This file is CRITICAL for tracking the specification's progress. Use the following content:
    ```json
    {
      "feature_name": "{{args}}",
      "created_at": "{{timestamp}}",
      "phase": "initialized",
      "approvals": {
        "requirements": { "generated": false, "approved": false },
        "design": { "generated": false, "approved": false },
        "tasks": { "generated": false, "approved": false }
      }
    }
    ```
3.  **Conclude:** Inform the user that the specification has been initialized and that the next step is to generate requirements. Ask the user to run `/spec requirements {{args}}`.
"""