description = "Generate the technical design for a spec after ensuring requirements are approved."
prompt = """
# Task: Technical Design Generation for '{{args}}'

You are an expert AI system architect. Your goal is to create a technical design for the specification **{{args}}**.

---
### PHASE 1: REQUIREMENTS APPROVAL
---
**Your Goal:** Ensure the requirements for this spec are approved before proceeding.

**Actions:**
1.  **Check State:** Read the metadata file at `.gemini/specs/{{args}}/spec.json`.
2.  **Verify Approval:** Check if `approvals.requirements.approved` is `true`. 
3.  **If Not Approved:**
    a.  Show the user the content of `.gemini/specs/{{args}}/requirements.md`.
    b.  Ask the user the exact question: "The requirements for '{{args}}' are not yet approved. Please review the requirements above. To approve them and proceed to the design phase, please respond with 'y'."
    c.  **Await user response.** If the user responds with 'y', proceed. Otherwise, stop.
    d.  **Update State on Approval:** If the user approved, use the `replace` tool to update `.gemini/specs/{{args}}/spec.json`. Find `"approved": false` for requirements and replace it with `"approved": true`.

---
### PHASE 2: DESIGN GENERATION
---
**Prerequisite:** Requirements are now approved.

**Actions:**
1.  **Load Context:**
    - Read the approved `.gemini/specs/{{args}}/requirements.md`.
    - Read all steering documents from `.gemini/steering/*.md` (`tech.md`, `structure.md`).
2.  **Analyze Codebase (MANDATORY):**
    - Conduct a deep analysis of the existing codebase to identify reusable patterns, components, and utilities.
3.  **Generate Document:** Create the content for `design.md` using the template from `.gemini/templates/spec/design-template.md`.
4.  **Save Document:** Save the content to `.gemini/specs/{{args}}/design.md` using the `write_file` tool.
5.  **Update State:** Use the `replace` tool to update `.gemini/specs/{{args}}/spec.json`. Find the line `"phase": "requirements-generated"` and replace it with `"phase": "design-generated"`. Also, update `approvals.design.generated` to `true`.
6.  **Request Approval:** Present the `design.md` to the user and ask for approval with the exact question: "Does the `design.md` look correct? If so, you can approve it by running `/spec tasks {{args}}` which will proceed to the next phase."
"""
