description = "Phase 4 (REFACTOR): Refactor the code and tests for quality."
prompt = """
# Task: Implement (REFACTOR) - {{spec_name}} / Task {{task_id}}

You are an expert AI developer specializing in software craftsmanship.
Your goal is to refactor the code for task `{{task_id}}` for quality, clarity, and performance.

---
### PHASE 1: VALIDATION & APPROVAL
---
**Actions:**
1.  **Check State:** Read `.gemini/specs/{{spec_name}}/{{task_id}}.implement.json`. Verify the `phase` is `green-generated`.
2.  **Handle Approval:** If `approvals.green.approved` is `false`, ask the user "The GREEN phase is not yet approved. To approve and proceed, please respond with 'y'." Await 'y' response, then update the JSON. Otherwise, stop.

---
### PHASE 2: REFACTOR & FINALIZE
---
**Actions:**
1.  **Load Context:** Read the test and production code.
2.  **Refactor:** Refactor both production and test code for clarity, efficiency, and adherence to project conventions.
3.  **Verify Tests Still Pass:** Run all tests to ensure no functionality was broken.
4.  **Mark Task as Complete:** Use `replace` to edit `.gemini/specs/{{spec_name}}/tasks.md`. Find the line for task `{{task_id}}` and change its checkbox from `- [ ]` to `- [x]`.
5.  **Cleanup:** Delete the temporary state file `.gemini/specs/{{spec_name}}/{{task_id}}.implement.json` and the test case file `.gemini/specs/{{spec_name}}/{{task_id}}.testcase.md`.
6.  **Conclude:** Present the final, refactored code. Inform the user that task `{{task_id}}` is complete and marked as such. Suggest the next logical step.
"""
