description = "Implement a specific task from a spec using TDD."
prompt = """
# Task: Implement Task '{{task_id}}' from Spec '{{spec_name}}'

You are an expert AI developer specializing in Test-Driven Development (TDD). Your goal is to implement the task with ID `{{task_id}}` from the specification `{{spec_name}}`.

---
### IMPLEMENTATION CYCLE
---
**Action:**
1.  **Load Context:** Read the files `.gemini/specs/{{spec_name}}/design.md` and `.gemini/specs/{{spec_name}}/tasks.md` to fully understand the task requirements and technical design.
2.  **Implement:** Follow this strict implementation cycle repeatedly until the task is complete:
    a.  **Design API & Invariants**: State the API contract and invariants from `design.md` you are implementing.
    b.  **Write a Failing Test (Red)**: Write a unit test that fails because the required functionality doesn't exist.
    c.  **Make the Test Pass (Green)**: Write the simplest code to make the test pass.
    d.  **Refactor**: Clean up the code while keeping all tests passing.
3.  **Mark Task as Complete:**
    - After the implementation is verified and complete, use the `replace` tool to edit `.gemini/specs/{{spec_name}}/tasks.md`.
    - Find the line for task `{{task_id}}` and change its checkbox from `- [ ]` to `- [x]`.
4.  **Conclude:** Provide the final code and confirm that the task has been marked as complete.
"""
