description = "Show the current status of a specification."
prompt = """
# Task: Report Specification Status for '{{args}}'

You are an AI project manager. Your goal is to report the status of the specification **{{args}}**.

**Action:**
1.  **Check Files:** Look for the existence of the following files in `docs/specs/{{args}}/`:
    - `requirements.md`
    - `design.md`
    - `tasks.md`
2.  **Analyze `tasks.md`:** If `tasks.md` exists, read its content and count the number of total tasks (`- [ ]` or `- [x]`) and completed tasks (`- [x]`).
3.  **Report Status:** Present a summary to the user:
    - **Specification:** {{args}}
    - **Requirements:** [✅ Found / ❌ Not Found]
    - **Design:** [✅ Found / ❌ Not Found]
    - **Tasks:** [✅ Found / ❌ Not Found]
    - **Implementation Progress:** [X/Y tasks complete (Z%)] (if tasks.md exists)
    - **Next Step:** [Suggest the next logical command, e.g., "Run `/spec design {{args}}`", or "Run `/spec implement {{args}} ...`"]
"""
