description = "Apply feature content to steering documents after implementation completion."
prompt = """
# Task: Apply Feature Content to Steering Documents for '{{args}}'

You are an expert AI documentation manager. Your goal is to update the steering documents with content from the completed feature specification **{{args}}**.

---
### PHASE 1: VALIDATION
---
**Your Goal:** Ensure the feature implementation is complete.

**Actions:**
1.  **Check State:** Read the metadata file at `docs/specs/{{args}}/spec.json`.
2.  **Verify Completion:** Check if the `"phase"` indicates completion (e.g., all tasks are marked as complete in `tasks.md`).
3.  **If Not Complete:** Inform the user that the feature implementation must be completed before applying to steering documents and stop.

---
### PHASE 2: STEERING DOCUMENT UPDATES
---
**Prerequisite:** Feature implementation is complete.

**Actions:**
1.  **Load Content:**
    - Read `docs/specs/{{args}}/requirements.md`
    - Read `docs/specs/{{args}}/design.md`
    - Read `docs/specs/{{args}}/user-doc.diff` (if it exists)
    - Read current steering documents: `product.md`, `tech.md`, `structure.md`, `manual.md`

2.  **Apply User Manual Diff:**
    - If `user-doc.diff` exists, apply the diff content to `docs/steering/manual.md`
    - Integrate the new feature documentation seamlessly into the existing manual structure
    - Ensure proper formatting and consistency with existing content

3.  **Update Product Document:**
    - Extract relevant product information from requirements and design
    - Update `docs/steering/product.md` with:
      - New capabilities/functions
      - Updated project goals/objectives
      - Modified success criteria/metrics
    - Preserve existing content while integrating new information

4.  **Update Technical Document:**
    - Extract relevant technical information from design document
    - Update `docs/steering/tech.md` with:
      - New technologies/frameworks/libraries used
      - Updated technical decisions and rationale
      - New development commands or tools
    - Preserve existing technical decisions while adding new ones

5.  **Update Structure Document:**
    - Extract structural changes from design document
    - Update `docs/steering/structure.md` with:
      - New directory structures or file organization
      - Updated naming conventions (if applicable)
      - New code organization principles (if applicable)
    - Preserve existing structure while documenting new additions

6.  **Cleanup:** Remove the temporary `user-doc.diff` file from `docs/specs/{{args}}/` as it has been applied.

7.  **Update State:** Use the `replace` tool to update `docs/specs/{{args}}/spec.json`. Add a field `"steering_applied": true` to mark this step as complete.

8.  **Conclude:** Present a summary of what was updated in each steering document. Inform the user that the feature **{{args}}** has been fully integrated into the project's steering documents and the specification process is now complete.
"""