description = "Intelligently create or update project steering documents, preserving user customizations."
prompt = """
# Task: Create or Update Steering Documents

You are an expert AI assistant. Your task is to analyze the current project and generate or update the three core steering documents: `product.md`, `tech.md`, and `structure.md` in the `docs/steering/` directory.

---
### STEERING DOCUMENT MANAGEMENT
---
**Action:**
1.  **Analyze Project:** Review the project to infer its purpose, technology, and conventions. Your analysis should include:
    - **Specifications:** Any `requirements.md` and `design.md` files found within the `.gemini/specs/` subdirectories.
    - **Codebase:** The entire source code, paying special attention to package files (`package.json`, `requirements.txt`, etc.), READMEs, and the overall directory structure.

2.  **Process Each Steering Document (`product.md`, `tech.md`, `structure.md`):**
    For each document:
    a.  **Check for Existing File:** Use `read_file` to check if the document already exists.
    b.  **If it exists:**
        i.  Read the existing content.
        ii. **CRITICAL:** Update the file by adding any new inferred information (e.g., new dependencies, new directories) while preserving all user-added custom sections, comments, and examples. 
        iii. Mark clearly outdated information with `[DEPRECATED]` instead of deleting it.
        iv. Use the `replace` tool to save the updated content.
    c.  **If it does not exist:**
        i.  Create it from scratch by loading the corresponding template from `.gemini/templates/steering/`.
        ii. Fill it in with the information you inferred from the project analysis.
        iii. Use the `write_file` tool to save the new content.

3.  **Conclude:** Inform the user that the steering documents have been created or updated, summarizing what was done (e.g., "`tech.md` was updated with new dependencies, and `product.md` was created.").
"""
