description = "Generate user manual diff for a specific feature after spec creation."
prompt = """
# Task: Generate User Manual Diff for '{{args}}'

You are an expert technical writer. Your goal is to create a user-facing documentation diff for the specification **{{args}}** that can be applied to the user manual.

---
### PHASE 1: VALIDATION
---
**Your Goal:** Ensure the specification has been initialized.

**Actions:**
1.  **Check State:** Read the metadata file at `docs/specs/{{args}}/spec.json`.
2.  **Verify Phase:** Confirm that the `"phase"` is `"initialized"`. If not, inform the user to run `/spec:create {{args}} "<description>"` first and stop.

---
### PHASE 2: USER DOCUMENTATION DIFF GENERATION
---
**Prerequisite:** Specification is initialized.

**Actions:**
1.  **Load Context:**
    - Read the `spec.json` file at `docs/specs/{{args}}/spec.json` and extract the value of the `description` key.
    - Read the existing user manual at `docs/steering/manual.md` to understand current content structure.
    - Perform a high-level analysis of the feature to understand user-facing aspects.

2.  **Generate User Documentation Diff:**
    - Based on the feature description from `spec.json`, create user-facing documentation content.
    - Focus on aspects that end-users need to know: installation steps, usage instructions, configuration options, examples, troubleshooting.
    - Format the content as a diff that can be applied to the existing user manual.
    - Include sections like:
      - Overview/Description of the new feature
      - Installation/Setup requirements (if any)
      - Usage examples with command-line syntax or UI steps
      - Configuration options
      - Common use cases
      - Troubleshooting tips

3.  **Save Diff File:** Save the generated diff content to `docs/specs/{{args}}/user-doc.diff` using the `write_file` tool.

4.  **Update State:** Use the `replace` tool to update `docs/specs/{{args}}/spec.json`. Add a new field `"user_doc_diff_generated": true` to track this step.

5.  **Request Next Step:** Present the generated diff to the user and inform them: "User documentation diff has been generated at `docs/specs/{{args}}/user-doc.diff`. Review the content, then proceed to requirements generation with `/spec:requirements {{args}}`."
"""